name: "publish"
on:
  push:
    branches:
      - "chat"

jobs:
  publish-tauri:
    permissions:
      contents: write # Important: required to create a GitHub release
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04, windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: swatinem/rust-cache@v2
        with:
          # Caches the target directory
          target-dir: target
          # Set the key to include the platform and architecture
          key: ${{ runner.os }}-${{ matrix.platform }}}-cargo
      - uses: actions/setup-node@v4
        with:
          node-version: lts

      - name: Install app dependencies
        run: yarn install # Or pnpm install, yarn install

      - name: Build and release the Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Your app's bundle identifier
          bundleIdentifier: com.horijin.dev
          # Set your dist path, if it is not the default
          # distPath: ../dist
